FROM microsoft/dotnet:2.0.0-sdk

ENV DOTNET_USE_POLLING_FILE_WATCHER 1
ENV ASPNETCORE_ENVIRONMENT Development

COPY ./src/Mutterblack.Core/*.csproj /tmp/
COPY ./Directory.Build.props /

WORKDIR /tmp

RUN dotnet restore

WORKDIR /app/Mutterblack.Core

ENTRYPOINT dotnet watch run --no-launch-profile
